# Numpy

In [1]:
#import numpy with alias
import numpy as np

In [2]:
l=[2,7,11]
l_array=np.array([2,7,11,13])
print(l)
print(l_array)

[2, 7, 11]
[ 2  7 11 13]


In [3]:
data=np.array([[2,9.0,2.4],[0.1,6.7,8.3]])
data

array([[2. , 9. , 2.4],
       [0.1, 6.7, 8.3]])

In [4]:
data*8

array([[16. , 72. , 19.2],
       [ 0.8, 53.6, 66.4]])

In [5]:


data+data

array([[ 4. , 18. ,  4.8],
       [ 0.2, 13.4, 16.6]])

In [6]:

data.shape

(2, 3)

In [7]:
data.dtype

dtype('float64')

# ***creating ndarray***

In [8]:
data1=[5,2,7,11,34.0]

In [9]:
arra1=np.array(data1)
arra1

array([ 5.,  2.,  7., 11., 34.])

In [10]:
data2=[2,4,6,8],[3,6,8,1]

In [11]:
arra2=np.array(data2)
arra2

array([[2, 4, 6, 8],
       [3, 6, 8, 1]])

In [12]:
arra2.ndim

2

In [13]:
arra2.shape


(2, 4)

In [14]:
arra2.dtype

dtype('int64')

In [15]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [17]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [18]:
#data type for ndarray
arra1=np.array([1,2,7],  dtype=np.float64)
arra2=np.array([1,2,7],  dtype=np.int32)
arra2

array([1, 2, 7], dtype=int32)

# **arithmetic with numpy array**

In [19]:
arr=np.array([[2.4,5.7,8.0] ,[2.7,8.2,9.7]])
arr

array([[2.4, 5.7, 8. ],
       [2.7, 8.2, 9.7]])

In [20]:
arr*arr

array([[ 5.76, 32.49, 64.  ],
       [ 7.29, 67.24, 94.09]])

In [21]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
arr<arr

array([[False, False, False],
       [False, False, False]])

# **Indexing and slicing**

In [23]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# **Numpy**

In [24]:
import numpy as np
#creating a 1-dimentional array
a=np.array([2,5,7,9])
a
#creating a 2-dimentional array
b=np.array([[3,7,7,9],[4,4,5,10]])
b


array([[ 3,  7,  7,  9],
       [ 4,  4,  5, 10]])

In [25]:
#shape and size of the array
a.size
a.shape



(4,)

In [26]:
#shape and size of the array
b.shape
b.size

8

In [27]:
#reshaping the array
c=np.reshape(a,(2,2))
c


array([[2, 5],
       [7, 9]])

In [28]:
#transpoting the array
d=np.transpose(b)
d


array([[ 3,  4],
       [ 7,  4],
       [ 7,  5],
       [ 9, 10]])

In [29]:
#mathmatical operation with arrays
x=[2,4,8]
y=[3,7,9]
print("array addition :"  , x+y)

print("array multiplication :"  , x*4)

array addition : [2, 4, 8, 3, 7, 9]
array multiplication : [2, 4, 8, 2, 4, 8, 2, 4, 8, 2, 4, 8]
